CREATE TABLE pairs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipe_id INTEGER NOT NULL,
    recipe_title VARCHAR (225) NOT NULL,
    recipe_image_url VARCHAR (225) NOT NULL,
    -- recipe_description VARCHAR (255) NOT NULL, 
    -- instructions VARCHAR (255) NOT NULL, 
    servings INTEGER NOT NULL,
    beverage_title VARCHAR (255) NOT NULL, 
    beverage_description VARCHAR (255) NOT NULL, 
    url VARCHAR (255) NOT NULL
);