CREATE TABLE drops (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    mal_id INTEGER NOT NULL,
    drop_description VARCHAR (225) NOT NULL,
    drop_type VARCHAR (255) NOT NULL, 
    drop_name VARCHAR (255) NOT NULL, 
    drop_description VARCHAR (255) NOT NULL, 
    url VARCHAR (255) NOT NULL, 
    image_url VARCHAR (255) NOT NULL
);